@url_dev=http://localhost:3056/v1/api

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: a1b03462bf6c55bfdc4e22b63dd17bba8899778e0e92b411da5b72e07e52a0f8b4bb8ed4267a608bc3bf74166fb6d491ffa36543b8a129e8bb7198a406af8660

{
    "name": "Shop TIPS",
    "email": "shoptipjs09@gmail.com",
    "password": "123456"
}


### login
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: a1b03462bf6c55bfdc4e22b63dd17bba8899778e0e92b411da5b72e07e52a0f8b4bb8ed4267a608bc3bf74166fb6d491ffa36543b8a129e8bb7198a406af8660


{
    "email": "shoptipjs09@gmail.com",
    "password": "123456"
}

### Logout 
POST {{url_dev}}/shop/logout
Content-Type: application/json
x-api-key: a1b03462bf6c55bfdc4e22b63dd17bba8899778e0e92b411da5b72e07e52a0f8b4bb8ed4267a608bc3bf74166fb6d491ffa36543b8a129e8bb7198a406af8660
x-client-id: 660ea8ace79436dd48ba6e43
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjBlYThhY2U3OTQzNmRkNDhiYTZlNDMiLCJlbWFpbCI6InNob3B0aXBqczA5QGdtYWlsLmNvbSIsImlhdCI6MTcxMjc1MTYwNSwiZXhwIjoxNzEyOTI0NDA1fQ.4EuOikEfGB26-17AE7HdzVkvuALMQAAHQMcLxcGbiiA

### HandlerRefreshToken
POST {{url_dev}}/shop/handlerRefreshToken
Content-Type: application/json
x-api-key: a1b03462bf6c55bfdc4e22b63dd17bba8899778e0e92b411da5b72e07e52a0f8b4bb8ed4267a608bc3bf74166fb6d491ffa36543b8a129e8bb7198a406af8660
x-client-id: 660ea8ace79436dd48ba6e43
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjBlYThhY2U3OTQzNmRkNDhiYTZlNDMiLCJlbWFpbCI6InNob3B0aXBqczA5QGdtYWlsLmNvbSIsImlhdCI6MTcxMjk4Nzg3MCwiZXhwIjoxNzEzMTYwNjcwfQ.6YpAiCdNa8h9QweT6GqAKQ2HwpKBMLovMqfvdOPR4ss
x-rtoken-id: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjBlYThhY2U3OTQzNmRkNDhiYTZlNDMiLCJlbWFpbCI6InNob3B0aXBqczA5QGdtYWlsLmNvbSIsImlhdCI6MTcxMjk4Nzg3MCwiZXhwIjoxNzEzNTkyNjcwfQ.GksAJ2_n9XqWczTotyQAYYbpZm2Q7BLrdB0mv0sPGHI