@url_dev=http://localhost:3056/v1/api

### Create new Product
POST {{url_dev}}/product
Content-Type: application/json
x-api-key: a1b03462bf6c55bfdc4e22b63dd17bba8899778e0e92b411da5b72e07e52a0f8b4bb8ed4267a608bc3bf74166fb6d491ffa36543b8a129e8bb7198a406af8660
x-client-id: 661cb823649f9632147a9405
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFjYjgyMzY0OWY5NjMyMTQ3YTk0MDUiLCJlbWFpbCI6InNob3B0aXBqczA5QGdtYWlsLmNvbSIsImlhdCI6MTcxMzE1ODI2NSwiZXhwIjoxNzEzMzMxMDY1fQ.Lm5rciD1NzFOsVzgayHmAD2nCSM5fZh4LHSFlUaaeAw

{
    "product_name": "Furniture" ,
    "product_thumb": "product_thumb",
    "product_description": "High-quality Furniture",
    "product_price": 100,
    "product_quantity": 10,
    "product_type": "Furniture",
    "product_attributes": {
        "brand": "MSI",
        "size": "M",
        "material": "Wood"
    }
}