@url_dev=http://localhost:3056/v1/api

### Create new Product
POST {{url_dev}}/product
Content-Type: application/json
x-api-key: a1b03462bf6c55bfdc4e22b63dd17bba8899778e0e92b411da5b72e07e52a0f8b4bb8ed4267a608bc3bf74166fb6d491ffa36543b8a129e8bb7198a406af8660
x-client-id: 660ea8ace79436dd48ba6e43
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjBlYThhY2U3OTQzNmRkNDhiYTZlNDMiLCJlbWFpbCI6InNob3B0aXBqczA5QGdtYWlsLmNvbSIsImlhdCI6MTcxMjkxMjUwNCwiZXhwIjoxNzEzMDg1MzA0fQ.vskVnEcoEPQzE9XDSZ1_i31hE-9Weld4t0NMce3Wg1g

{
    "product_name": "New Jeans 2" ,
    "product_thumb": "product_thumb",
    "product_description": "High-quality denim jeans 2",
    "product_price": 50,
    "product_quantity": 5,
    "product_type": "Clothing",
    "product_attributes": {
        "brand": "Levi 2",
        "size": "M",
        "material": "Denim"
    }
}